### ISSUE TITLE
pod continuously restarted because LivenessProbe port returns 404

### ISSUE THREAD

**Issue by ywysuibian** [interconnectedcloud/qdrouterd-operator#21]

**Comment by grs** [comment]
What version of the operator are you using and what image?

**Comment by ywysuibian** [comment]
@grs thank you.
I am using
quay.io/interconnectedcloud/qdrouterd-operator:latest
quay.io/interconnectedcloud/qdrouterd:1.5.0

**Comment by ajssmith** [comment]
With the qdrouterd-operator:latest you need to use
quay.io/interconnectedcloud/qdrouterd:1.6.0

**Comment by ywysuibian** [comment]
Thank you @ajssmith 
I will give it a try

**Comment by ywysuibian** [comment]
close this issue because 1.6.0 works well
